### ISSUE TITLE
Error when installing (Description file)

### ISSUE THREAD

**Issue by ghost** [onaio/ona.R#11]
I am getting an error after 

`library(devtools)
install_github("onaio/ona.R")`
## Error message:

 installing _source_ package 'ona' ...
Error : Invalid DESCRIPTION file

Malformed Depends or Suggests or Imports or Enhances field.
Offending entries:
  Suggests:testthat
Entries must be names of packages optionally followed by '<=' or '>=',
white space, and a valid version number in parentheses.

See section 'The DESCRIPTION file' in the 'Writing R Extensions'
## manual.

Suspected error source:
[DESCRIPTION.txt](https://github.com/onaio/ona.R/files/369578/DESCRIPTION.txt)

Row 29 at the very end of the attached DESCRIPTION file form from the ona.R-master zip:
"Suggests:testthat"
seems to cause the error. I guess this line can be deleted?

**Comment by jmunene** [comment]
Hi Seb,

I've tried installing the package and it works for me. I started by `library(devtools)`, after the library has loaded, I entered `install_github('onaio/ona.R')`.

If still having issues, please let us know the version of R you're using. You can also have a look at our blog on how to install and use ona.R [here](https://blog.ona.io/general/2016/04/15/Ona-R-Integration.html)

**Comment by joshuamosesb** [comment]
Hi, @jmunene as suggested by @ghost, could you pls check the [DESCRIPTION.txt](https://github.com/onaio/ona.R/files/369578/DESCRIPTION.txt) file? I've added the : https://github.com/onaio/ona.R/commit/8edcca7063ae1c7028d8ebbab5c74803facbe22a?diff=split#r31676148

**Comment by olanderb** [comment]
I'm having the same issue as @jjoshuamosesb, can you look into this?

**Comment by muneneg** [comment]
@olanderb @joshuamosesb Apologies for not getting back to you earlier, am currently working on fixing these issues.

**Comment by bcheye** [comment]
This issue is fixed.
