### ISSUE TITLE
Unable to import data into R

### ISSUE THREAD

**Issue by samwata** [onaio/ona.R#29]
I am getting the attached error when I try to import data into R

Steps to reproduce the error
```
#Download dev tools library
install.packages("devtools", dependencies = TRUE)

#Check if dev tools library has been installed
library(devtools)
install_github('onaio/ona.R')

#Check if ona library has been installed
library(ona)

# Download the dataset
good_eats <- onaDownload("good_eats", "mberg","mberg")
```

![image](https://user-images.githubusercontent.com/23456184/154034724-89304037-f515-4864-961c-a7b323a43a6d.png)

> good_eats <- onaDownload("good_eats", "mberg","mberg")
Error in function (type, msg, asError = TRUE)  : 
  error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
>

**Comment by George-Kamau** [comment]
From the error we are getting when trying to connect to ONA, it seems there is a connection error when trying to reach the ONA Data API, specifically, something about the TLS version. I found some information about this error [here](https://stackoverflow.com/questions/44316292/ssl-sslerror-tlsv1-alert-protocol-version). 


You can find the R script being used to call the API [here](https://github.com/onaio/ona.R/blob/master/R/ona.R). Specifically, the endpoint being used by the `onaDownload` function looks like this: `https://api.ona.io/ <account>/forms/<formName>/<form.json> or <data.csv>`

**Comment by eochieng-lab** [comment]
I'm going to close this issue for now since its been open for over a year and there is no work that is currently being put into addressing it.

**Comment by mbaldassaro** [comment]
A workaround:

```
library(httr)
library(jsonlite)

api_token <- "your api token"
form_id <- "your form id"

api_url <- paste0("https://api.ona.io/api/v1/data/", form_id)

headers <- c(
  Authorization = paste("Token", api_token)
)

response <- GET(api_url, add_headers(.headers=headers))

if (http_status(response)$category == "Success") {
  response_data <- fromJSON(content(response, "text"))
} else {
  cat("API request failed with status:", http_status(response)$reason, "\n")
}

```
