### ISSUE TITLE
Travis build failures when running ona.R package

### ISSUE THREAD

**Issue by Chepkeitany** [onaio/ona.R#6]
Context: ona.R package is a fork from formhub.R.
Integrated withTravis CI.

@jmunene and I have experienced some failures that probably may need change of code.

Here are some of the screenshots:
<img width="903" alt="screen shot 2016-04-12 at 16 03 14" src="https://cloud.githubusercontent.com/assets/3312861/14461046/888e814c-00c9-11e6-86d4-4705208dbffc.png">
Found some helpful links on stackoverflow http://stackoverflow.com/questions/31132552/no-visible-global-function-definition-for-median
<img width="887" alt="screen shot 2016-04-12 at 16 04 21" src="https://cloud.githubusercontent.com/assets/3312861/14461052/92ec234c-00c9-11e6-88eb-4b9c644462d0.png">

Some helpful link too
http://stackoverflow.com/questions/9900134/is-it-bad-practice-to-access-s4-objects-slots-directly-using

**Comment by Chepkeitany** [comment]
A useful link too http://adv-r.had.co.nz/S4.html

**Comment by jmunene** [comment]
Another useful [link](http://stackoverflow.com/questions/16387939/how-to-create-a-sub-class-of-data-frame-with-additional-features)

**Comment by pld** [comment]
a lot of the failures look like they're reference R libraries that probably haven't loaded, are you sure the libraries are being loaded correctly in the test environment?

**Comment by pld** [comment]
Looks like you have this passing?

**Comment by jmunene** [comment]
@pld Most of the errors were on the examples, will need to re-write the whole code again.
